frontend/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('detail/', views.detail, name='detail'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register, name='register'),
    path('search/', views.search, name='search'),
    path('product/', views.product, name='product'),
    path('product/<int:pk>/', views.detail, name='detail'),
    path('download/<int:product_id>/', views.download_image, name='download_image'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('profile/<int:user_id>/', views.profile, name='profile'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('userprofile/<int:user_id>/', views.userprofile, name='userprofile'),
    path('category_user/<int:maincategory_id>/', views.category_user, name='category_user'),
    path('add-product/<int:category_id>/', views.add_product, name='add_product_view'),
    path('delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('follow/<int:user_id>/', views.follow_user, name='follow_user'),
    path('unfollow/<int:user_id>/', views.unfollow_user, name='unfollow_user'),
    path('add_to_wishlist/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/', views.wishlist_view, name='wishlist_view'),
    path('maincategory_detail/<int:id>/', views.maincategory_detail, name='maincategory_detail'),
    path('category_detail/<int:id>/', views.category_detail, name='category_detail'),
    path('reset_password',auth_views.PasswordResetView.as_view(template_name='password/password_reset_form.html'),name="reset_password"),
    path('reset_password_sent',auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'),name="password_reset_done"),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password/password_reset_confirm.html'),name="password_reset_confirm"),
    path('reset_password_complete',auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'),name="password_reset_complete"),
]

studio/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
    # path('cart/', include('cart.urls')),
    # path('payment/', include('payment.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
from django.utils import timezone
# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # Add any additional fields you want here, e.g., profile picture, bio, etc.
    bio = models.TextField(max_length=500, blank=True)
    profile_image = models.ImageField(upload_to='uploads/profile_pics/', default='uploads/profile_pics/default.png', blank=True, null=True)
    following = models.ManyToManyField('self', symmetrical=False, related_name='followers', blank=True)

    def __str__(self):
        return f"{self.user.first_name} ({self.user.username})"
    
    def follow(self, profile):
        """Follow another user's profile."""
        self.following.add(profile)
        
    def unfollow(self, profile):
        """Unfollow another user's profile."""
        self.following.remove(profile)
   


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
    instance.userprofile.save()
class Subscriber(models.Model):
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.email

class ContactMessage(models.Model):
    name = models.CharField(max_length=255)
    subject = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=20, blank=True)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Message from {self.name} - {self.email}"


class MainCategory(models.Model):
	name = models.CharField(max_length=50)
	image = models.ImageField(upload_to='uploads/maincategory/', default="none")

	def __str__(self):
		return self.name

	#@daverobb2011
	class Meta:
		verbose_name_plural = 'maincategories'


class Category(models.Model):
	name = models.CharField(max_length=50)
	image = models.ImageField(upload_to='uploads/category/', default="none")
	maincategory = models.ForeignKey(MainCategory, on_delete=models.CASCADE, default=1)


	def __str__(self):
		return self.name

	#@daverobb2011
	class Meta:
		verbose_name_plural = 'categories'

class Product(models.Model):
    name = models.CharField(max_length=200)
    created_at = models.DateTimeField(default=timezone.now)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    image = models.ImageField(upload_to='uploads/product/')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)


    def __str__(self):
	    return self.name
      
class ProductReview(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=1)  # Rating out of 5

    class Meta:
        unique_together = ('product', 'user')  # Ensures a user can only review a product once

    def __str__(self):
        return f"{self.product.name} - {self.rating} Stars"
    

class Wishlist(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='wishlists')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='wishlist_items')

    class Meta:
        unique_together = ('user', 'product')

    def __str__(self):
        return f"{self.user}'s wishlist item: {self.product.name}"

frontend/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import ContactMessage, Subscriber
from django.contrib.auth.models import User
from .models import UserProfile, Product,  ProductReview


class ProductReviewForm(forms.ModelForm):
    class Meta:
        model = ProductReview
        fields = ['rating']
        widgets = {
            'rating': forms.RadioSelect(choices=[(i, str(i)) for i in range(1, 6)])
        }


class ProfileImageForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=False, label='First Name')
    last_name = forms.CharField(max_length=30, required=False, label='Last Name')
    username = forms.CharField(max_length=150, required=True, label='Username')

    class Meta:
        model = UserProfile
        fields = ['profile_image', 'bio']  # UserProfile fields

    def __init__(self, *args, **kwargs):
        # Get the 'user' object passed through the form instance
        self.user = kwargs.pop('user', None)
        super(ProfileImageForm, self).__init__(*args, **kwargs)

        # Initialize the form fields with the user's existing data
        if self.user:
            self.fields['first_name'].initial = self.user.first_name
            self.fields['last_name'].initial = self.user.last_name
            self.fields['username'].initial = self.user.username

    def save(self, commit=True):
        # Save the UserProfile data
        profile = super(ProfileImageForm, self).save(commit=False)
        if commit:
            profile.save()

        # Save the User data
        if self.user:
            self.user.first_name = self.cleaned_data['first_name']
            self.user.last_name = self.cleaned_data['last_name']
            self.user.username = self.cleaned_data['username']
            self.user.save()

        return profile

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['bio', 'profile_image']

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'image', 'category']


class SubscriberForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = ['email']


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ['name', 'subject', 'email', 'phone', 'message']


class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password']
        widgets = {
            'password': forms.PasswordInput(),
        }

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        self.fields['username'].help_text = '<br><span class="form-text text-muted"><small>Allowed Letters, digits, @/./+/-/_ and max char 150 .</small></span>'
        self.fields['username'].label = 'Username *'
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'Enter Your Username'

        self.fields['first_name'].label = 'First Name'
        self.fields['first_name'].widget.attrs['class'] = 'form-control'
        self.fields['first_name'].widget.attrs['placeholder'] = 'Enter Your First Name'

        self.fields['last_name'].label = 'Last Name'
        self.fields['last_name'].widget.attrs['class'] = 'form-control'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Enter Your Last Name'

        self.fields['email'].label = 'Email Adress *'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'Enter Your Email'

        self.fields['password'].label = 'Password *'
        self.fields['password'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['placeholder'] = 'Enter Your Password'

frontend/templates/about.html
{%extends 'base.html'%}

{%block content%}

<style>
	#about-style{
		padding: 30px 80px;
		word-spacing: 4px;
		line-height: 1.5em;
		font-size:  18px;
	}
</style>


<section id="about">
<div class="container" >
 <div class="row">
	<div class="example_h_1 clearfix" >
	<div class="example_h_1l clearfix" style="background: #CFFFDC">
		<div class="list_1 text-center clearfix" >
			<div class="col-sm-12">
			<br><br>  
			 <h2 class="mgt">Our Story</h2>	 
			</div>
		   </div>
	<p id="about-style"> At A4 Studio, we believe in the power of creativity to inspire, connect, and transform. Our platform is a vibrant hub where artists and art enthusiasts from around the world come together to discover, share, and celebrate the beauty of visual expression.
        <br><br>
		Founded with a passion for art and technology, A4 Studio bridges the gap between creators and collectors. Whether you're seeking to showcase your latest masterpiece or searching for the perfect artwork to bring your vision to life, our platform is designed to foster collaboration and creativity. From stunning paintings and intricate illustrations to dynamic digital art and beyond, we are dedicated to offering a diverse and ever-expanding collection of works.
		<br><br>
		But we’re more than just a gallery. We empower artists to share their work with the world, offering tools to build a following, gain feedback through reviews, and connect with other creators. For art lovers, our personalized features allow you to curate your own collections, add items to your wishlist, and support the creators you admire.
		<br><br>
		At the heart of A4 Studio is a commitment to creativity without limits. Every artist’s journey is unique, and our platform is here to celebrate that individuality, helping you showcase your talents, connect with an audience, and be part of a global art community.
		<br><br>
		Join us and be part of something extraordinary—where art meets innovation, and creativity knows no bounds.</p>
		<br>
	</div>
   </div>
 </div>
</div>
</section>



<section id="connect" class="clearfix">
 <div class="container">
  <div class="row">
   <div class="col-sm-12 space_all">
    <div class="connect_1 clearfix">
	 <div class="col-sm-3 connect_1m">
	  <div class="connect_1l clearfix">
	    <span><i class="fa fa-paint-brush"></i></span>
	  </div>
	  <div class="connect_1r clearfix">
	   <h4>Unique Artworks</h4>
	   <p>Explore and Discover Unique Artworks</p>
	  </div>
	 </div>
	 <div class="col-sm-3 connect_1m">
	  <div class="connect_1l clearfix">
	    <span><i class="fa fa-upload"></i></span>
	  </div>
	  <div class="connect_1r clearfix">
	   <h4>Upload Art Pieces</h4>
	   <p>Showcase your talent to the world.</p>
	  </div>
	 </div>
	 <div class="col-sm-3 connect_1m">
	  <div class="connect_1l clearfix">
	    <span><i class="fa fa-heart"></i></span>
	  </div>
	  <div class="connect_1r clearfix">
	   <h4>Create Collections</h4>
	   <p>Add favorite items to your wishlist.</p>
	  </div>
	 </div>
	 <div class="col-sm-3 connect_1m border_none">
	  <div class="connect_1l clearfix">
	    <span><i class="fa fa-star"></i></span>
	  </div>
	  <div class="connect_1r clearfix">
	   <h4>Review visuals</h4>
	   <p>Review the itemms you like or dislike.</p>
	  </div>
	 </div>
	</div>
   </div>
  </div>
 </div>
</section>

<section id="testim">
	<div class="container">
	 <div class="row">
	  <div class="list_1 text-center clearfix">
	   <div class="col-sm-12">  
		<h2 class="mgt">Happy Clients</h2>
	   </div>
	  </div>
	  <div class="testim_1 clearfix">
	   <div class="col-sm-4">
		<div class="testim_1i clearfix">
		  <div class="testim_1i1 clearfix"><span><i class="fa fa-quote-left"></i></span></div>
		  <div class="testim_1i2 clearfix">
			<p class="col_2">This platform has truly transformed the way I share my art. The ability to showcase my work to a global audience and receive feedback has been invaluable. </p>
			<div class="testim_1i2i clearfix">
			  <img src="../../static/img/user1.jpg" class="img-circle" alt="abc" width="60px" height="60px">
			  <h4 class="col_1 mgt">Sarah Mitchell<br> <span class="small_tag col_2">Digital Artist</span></h4>
			</div>
		  </div>
		</div>
	   </div>
	   <div class="col-sm-4">
		<div class="testim_1i clearfix">
		  <div class="testim_1i1 clearfix"><span><i class="fa fa-quote-left"></i></span></div>
		  <div class="testim_1i2 clearfix">
			<p class="col_2">As a passionate art collector, this website has become my go-to for discovering unique and stunning pieces and the curated categories make browsing a breeze.</p>
			<div class="testim_1i2i clearfix">
			  <img src="../../static/img/user3.jpg" class="img-circle" alt="abc" width="60px" height="60px">
			  <h4 class="col_1 mgt">Jason Carter<br> <span class="small_tag col_2">Art Collector</span></h4>
			</div>
		  </div>
		</div>
	   </div>
	   <div class="col-sm-4">
		<div class="testim_1i clearfix">
		  <div class="testim_1i1 clearfix"><span><i class="fa fa-quote-left"></i></span></div>
		  <div class="testim_1i2 clearfix">
			<p class="col_2">The user experience on this platform is fantastic! Uploading and organizing my digital art has never been easier. I also appreciate the wishlist feature."</p>
			<div class="testim_1i2i clearfix">
			  <img src="../../static/img/user2.jpg" class="img-circle" alt="abc" width="60px" height="60px">
			  <h4 class="col_1 mgt">Emily Rivera<br> <span class="small_tag col_2">Graphic Designer</span></h4>
			</div>
		  </div>
		</div>
	   </div>
	  </div>
	 </div>
	</div>
   </section>

{%endblock%}

frontend/templates/base_product.html
{%load static%}

<style>
    .collapseIcon {
        cursor: pointer;
        display: inline-block;
        margin-left: 10px;
    }
    
    .clickable {
        display: none; /* Initially hide the categories */
    }
    
    .collapseIcon.active {
        transform: rotate(180deg);
        transition: transform 0.3s ease;
    }
    
</style>
<section id="list_pg" class="clearfix"> 
    <div class="container">
     <div class="row">
      <div class="list_pg_1 clearfix">
       <div class="col-sm-3">
         <div class="list_pg_1l clearfix">
            <div class="center_shop_1li clearfix product_1i">
                <h5 class="mgt">SEARCH</h5>
                <form action="{% url 'search' %}" method="get">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control form_2" placeholder="Search Here...">
                        <span class="input-group-btn">
                            <button class="btn btn-primary" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </form>
            </div>            
            
        <div class="product_1i clearfix">
          <h5 class="mgt">HOME</h5>
          <div class="ziehharmonika">
            {% for maincategory in maincategories %}
            <h3 data-prefix="★" class="active">
                <a href="{% url 'maincategory_detail' maincategory.id %}">{{ maincategory.name }}</a>
                <div class="collapseIcon">+</div>
            </h3>
            <div class="clickable" style="display: none;">
                <ul>
                    {% for category in maincategory.category_set.all %}
                        <li>
                            <a href="{% url 'category_detail' category.id %}">{{ category.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% endfor %}        
          </div>
      </div>
                      
                      

      </div>
 </div>
 <br>

 <script>
    $(document).ready(function() {
        $('h3 .collapseIcon').on('click', function() {
            var $this = $(this);
            var $clickable = $this.closest('h3').next('.clickable');
            
            $clickable.slideToggle(); // Toggle the visibility of categories
            
            // Toggle the icon between '+' and '-'
            if ($this.text() === "+") {
                $this.text("-");
            } else {
                $this.text("+");
            }
        });
    });
    
 </script>

frontend/templates/category_detail.html
{%extends 'base.html'%}

{%block content%}

<style>
    .icon-style:hover {
        color: white;
        background-color: white;
    }
</style>



{%include 'base_product.html' %}

 <div class="col-sm-9">
   <div class="list_pg_1r clearfix">
	 <div class="product_1r clearfix">
	<div class="center_product_1r2 clearfix">
   <div class="col-sm-6">
	<div class="center_product_1r2l clearfix">
	  <p class="mgt">There are {{total_products}} products in {{category.name}}.</p>
	</div>
   </div>
   <div class="col-sm-6">
    <div class="center_product_1r2r text-right clearfix">
        <div class="col-sm-6" style="padding-top: 8px; text-align:left; width:30%; padding-right:0;">
        <h5 class="mgt" >SORT BY</h5>
        </div>
        <div class="col-sm-6" style="width:70%; padding-left:0;">
        <form method="GET" id="sortForm">
            <select style=" width:100%;" class="form-control" id="subject" name="sort" onchange="document.getElementById('sortForm').submit();">
                <option value="">Select...</option>
                <option value="rating_asc">Rating, Low To High</option>
                <option value="rating_desc">Rating, High To Low</option>
                <option value="name_asc">Alphabetically, A-Z</option>
                <option value="name_desc">Alphabetically, Z-A</option>
                <option value="date_desc">Date, New To Old</option>
                <option value="date_asc">Date, Old To New</option>
            </select>
        </form>
    </div>
    </div>
</div>
</div>
	
<div class="list_pg_1r1 clearfix">
    {% if products %}
        {% for product in products %}
        <div class="col-sm-4 space_left">
            <div class="list_2im clearfix">
                <div class="list_2imi clearfix">
                    <img src="{{ product.image.url }}" class="iw" alt="abc" width="300px" height="350px">
                </div>
                <div class="list_2imi1 clearfix">
                    <h5 class="mgt normal">New</h5>
                </div>
                <div class="list_2imi2 clearfix">
                    <span><a href="{% url 'detail' product.id %}"><i class="fa fa-eye"></i></a></span>
                </div>
            </div>
            <div class="list_2im1 clearfix" style="margin-bottom:20px;">
                <h4><a href="{% url 'detail' product.id %}">{{ product.name }}</a></h4>
                <div class="col-sm-6">
                <h6><a class="button mgt" href="{% url 'detail' product.id %}">View</a></h6>
                </div>
                <div class="col-sm-6">
                {% if user.is_authenticated %}
                    <form action="{% url 'add_to_wishlist' product.id %}" method="POST">
                        {% csrf_token %}
                        <h6><button style="border:none;" class="button mgt" type="submit"><i class="fa fa-heart-o"></i></button></h6>
                    </form>
                    {% else %}
                        <h6><a href="{% url 'login' %}" class="button mgt"><i class="fa fa-heart-o"></i></a></h6>
                    {% endif %}
                </div>
            </div>
            </div>
        {% endfor %}
    {% else %}
        <p>No products available in this category.</p>
    {% endif %}
    
    </div>
		 <div class="pages clearfix text-center" >
		 <ul>
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-chevron-left" style="color: black;"></i></a></li>
            {% endif %}
            
            
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.paginator.num_pages }}"><i class="fa fa-chevron-right" style="color: black;"></i></a></li>
            {% endif %}
		   </ul>
	   </div>
	  </div>
	 </div>
	</div>
   </div>
  </div>
</section>

{%endblock%}

frontend/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link href="../../static/css/profile.css" rel="stylesheet">

<div class="profile-container">
    <!-- Edit profile option -->
    {% if is_editing %}
        <form method="post" enctype="multipart/form-data" class="profile-edit-form" id="form-group">
            {% csrf_token %}
            <div>
                <label for="id_username">Username:</label>
                {{ form.username }}
            </div>

            <div>
                <label for="id_first_name">First Name:</label>
                {{ form.first_name }}
            </div>

            <div>
                <label for="id_last_name">Last Name:</label>
                {{ form.last_name }}
            </div>

            <div>
                <label for="id_bio">Bio:</label>
                {{ form.bio }}
            </div>

            <div>
                <label for="id_profile_image">Profile Image:</label>
                {{ form.profile_image }}
            </div>
            
            <button class="button mgt" type="submit">Save Changes</button>

        </form>


    {% else %}

        <!-- Profile page shown to the user if it is not editing-->

        <div class="profile-info">
            {% if user_profile.profile_image %}
                <img src="{{ user_profile.profile_image.url }}" alt="Profile Image" width="80px" height="80px">
            {% else %}
                <img src="{% static 'uploads/profile_pics/default.png' %}" alt="Default Profile Image" width="80px" height="80px">
            {% endif %}
            <div class="profile-details">
                <h4>{{ full_name }}</h4>
                <p>@{{ user.username }}</p>
                <p>{{ user.userprofile.bio }}</p>
            </div>
            <a href="?edit=true" class="button mgt">Edit Profile</a>
        </div>
        
        
        <div class="mt-4">
            <ul>
                <li>
                    <a href="?show=following" class="col_1 bold">Favorite Creators</a>
                </li>
                    <ul class="following-list">
                        {% if show_following %}
                        {% for followed_user in following_list %}
                            <div class="col-sm-6" style="margin:0; padding: 0; ">
                            <li><h5><a href="{% url 'profile' followed_user.user.id %}">{{ followed_user.user.username }}</a></h5></li>
                            </div>
                            <!-- Display follow/unfollow button based on whether the user is already following the profile owner -->
                            <div class="col-sm-6 text-right" style="margin:0; padding:0">
                                <div style="padding-bottom:10px;">
                            {% if request.user != followed_user.user %}
                                {% if followed_user in request.user.userprofile.following.all %}
                                    <a href="{% url 'unfollow_user' followed_user.user.id %}" class="button mgt">Unfavorite</a>
                                {% else %}
                                    <a  href="{% url 'follow_user' followed_user.user.id %}" class="button mgt">Add to Favorites</a>
                                {% endif %}
                            </div>
                            {% endif %}
                           </div>
                        {% empty %}
                            <li>You've not added anyone yet.</li>
                        {% endfor %}
                    {% endif %}    
                    </ul>

                <li class="wishlist-item">
                    <a class="col_1 bold" href="?show=wishlist_items">Wishlist</a>
                    {% if show_wishlist %}
                        <ul class="product-list list_pg_1r1 clearfix">
                            <div class="clearfix">
                                {% for item in wishlist_items %}
                                <div class="col-sm-4 space_left">
                                    <div class="list_2im clearfix">
                                        <div class="list_2imi clearfix">
                                            <img src="{{ item.product.image.url }}" class="iw" alt="Product Image" width="300px" height="200px">
                                        </div>
                                    </div>
                                    <div class="list_2im1 clearfix">
                                        <h4><a href="{% url 'detail' item.product.id %}">{{ item.product.name }}</a></h4>
                                        <div class="col-sm-6">
                                        <h6><a class="button mgt" href="{% url 'detail' item.product.id %}">View</a></h6>
                                        </div>
                                    </div>
                                </div>
                                {% empty %}
                                <li>There's nothing in wishlist yet.</li>
                                {% endfor %}
                            </div>
                        </ul>
                    {% endif %}
                </li>
                    
            </ul>

            <ul class="category-list">
                <div class="ziehharmonika">
                    <h3 data-prefix="★" class="active">
                        Upload Products Here.
                        <div class="collapseIcon">+</div>
                    </h3>
                    <div class="clickable" style="display: none;">
                        <ul style="list-style-type: none;">
                            {% for maincategory in maincategories %}
                            <li>
                                <a class="col_1 bold" href="{% url 'category_user' maincategory.id %}">~ {{ maincategory.name }}</a>
                            </li>
                            {% endfor %} 
                        </ul>
                    </div>       
                </div>
            </ul>
        </div>
        
        <div class="mt-4">
            <h5>Your Products</h5>
            <ul class="product-list list_pg_1r1 clearfix">
                <div class="clearfix">
                    {% for product in user_products %}
                    <div class="col-sm-4 space_left">
                        <div class="list_2im clearfix">
                            <div class="list_2imi clearfix">
                                <img src="{{ product.image.url }}" class="iw" alt="Product Image" width="300px" height="200px">
                            </div>
                        </div>
                        <div class="list_2im1 clearfix">
                            <h4><a href="{% url 'detail' product.id %}">{{ product.name }}</a></h4>
                            <div class="col-sm-6">
                                <h6><a class="button mgt" href="{% url 'detail' product.id %}">View</a></h6>
                            </div>
                            <div class="col-sm-6">
                                <form action="{% url 'delete_product' product.id %}" method="POST" style="display:inline;">
                                    {% csrf_token %}
                                    <h6><button style="border:none;" type="submit" class="button mgt">Delete</button></h6>
                                </form>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                    <li>No products added yet.</li>
                    {% endfor %}
                </div>
            </ul>
        </div>
         
    {% endif %}
</div>

<!-- For + sign functionality  -->
<script>
    $(document).ready(function() {
        $('h3 .collapseIcon').on('click', function() {
            var $this = $(this);
            var $clickable = $this.closest('h3').next('.clickable');
            
            $clickable.slideToggle(); // Toggle the visibility of categories
            
            // Toggle the icon between '+' and '-'
            if ($this.text() === "+") {
                $this.text("-");
            } else {
                $this.text("+");
            }
        });
    });
    
 </script>

{% endblock %}